### ISSUE TITLE
thanks and comments

### ISSUE THREAD

**Issue by andreakoelzsch** [CodenameGreyFox/DetectionOfStationarity#1]
Dear CodenameGreyFox,
Thanks a lot for your contribution to MoveApps and the EMAC23 coding challenge!
I have built your App (in the later version 2) into the system, please try out if it behaves as expected. I have done this to speed up the process, but what we do need for full consideration of the App is to please return the input data at the end of your App (simply return(data)) so that it can be integrated into a workflow with other Apps following after. Please not that also in the documentation (readme.md IO types - output). That would require submission of a new version that I am happy to build.
Thanks!
Andrea

**Comment by CodenameGreyFox** [comment]
Hello,

It already does that so that it acts as a pass-through (the return(data) thing).

Once I checked it worked in the site I was going to give an option of filtering the stationary individuals, but for now, that is exactly what it does.

Thanks for the reply!
Tomé

**Comment by andreakoelzsch** [comment]
thanks so much for the reply, I see it now too, must have mixed up with something else, sorry. All good to go then.

**Comment by CodenameGreyFox** [comment]
No problem! I have now added the filtering functionality I talked about and updated it on MoveApps.

**Comment by andreakoelzsch** [comment]
new App version is built, thanks!
